name: main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -alF /lib/modules/5.11.0-1028-azure
      - name: Install ALSA
        run: sudo modprobe snd-dummy

